# Generated by Django 5.0.6 on 2024-08-29 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('AdminMessage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Question', models.JSONField()),
                ('Test_Cases', models.JSONField()),
                ('Examples', models.JSONField()),
                ('Level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchName', models.CharField(default='N/A', max_length=25)),
                ('Course', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BatchMessagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('BatchMessage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchToStudentMessagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(max_length=255)),
                ('StudentId', models.IntegerField(default=0)),
                ('BatchMessage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseFeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('FeedbackData', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('Tutors', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.JSONField()),
                ('Username', models.CharField(default='N/A', max_length=255, unique=True)),
                ('Email', models.EmailField(default='N/A', max_length=254, unique=True)),
                ('Phone', models.CharField(default='N/A', max_length=255, unique=True)),
                ('Password', models.CharField(default='N/A', max_length=255)),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('User', models.CharField(default='User', max_length=255)),
                ('Permission', models.CharField(default='Access', max_length=255)),
                ('AddedBy', models.CharField(default='Self', max_length=255)),
                ('Joined_At', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementFeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('FeedbackData', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacementPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.JSONField()),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Company_Name', models.CharField(default='N/A', max_length=255)),
                ('Post_Link', models.CharField(default='N/A', max_length=255)),
                ('From_Date', models.CharField(max_length=255)),
                ('To_Date', models.CharField(max_length=255)),
                ('Description', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SendMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255)),
                ('OTP', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='SendOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(max_length=255)),
                ('OTP', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal_Info', models.JSONField()),
                ('Educational_Info', models.JSONField()),
                ('Placement_Info', models.JSONField()),
                ('Status', models.CharField(default='Active', max_length=255)),
                ('Access', models.CharField(default='Granted', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMessagesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('StudentMessage', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BatchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchName', models.CharField(default='N/A', max_length=25)),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('Date', models.CharField(default='N/A', max_length=255)),
                ('Attendance_Type', models.CharField(default='N/A', max_length=255)),
                ('BatchID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.batchdata')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Date', models.CharField(default='N/A', max_length=255)),
                ('Attendance_Type', models.CharField(default='N/A', max_length=255)),
                ('StudentID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.studentdata')),
            ],
        ),
    ]
