# Generated by Django 5.0.6 on 2024-08-29 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0002_alter_adminmessages_adminmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersLoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.JSONField(default=dict)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('User', models.CharField(default='User', max_length=255)),
                ('Permission', models.CharField(default='Access', max_length=255)),
                ('AddedBy', models.CharField(default='Self', max_length=255)),
                ('Joined_At', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
