# Generated by Django 5.0.6 on 2024-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0003_userslogindata_delete_logindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='BatchName',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Course',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Email',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Phone',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
