# Generated by Django 5.0.6 on 2024-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0004_studentdata_batchname_studentdata_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='Access',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Permission',
            field=models.CharField(default='Access', max_length=25),
        ),
    ]
