# Generated by Django 5.0.6 on 2024-08-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0005_remove_studentdata_access_studentdata_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchattendance',
            name='BatchID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.batchdata'),
        ),
    ]
