# Generated by Django 5.0.6 on 2024-08-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0006_alter_batchattendance_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtostudentmessagesdata',
            name='StudentId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='StudentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.studentdata'),
        ),
    ]
