# Generated by Django 5.0.6 on 2024-08-30 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0007_alter_batchtostudentmessagesdata_studentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchattendance',
            name='BatchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.batchdata'),
        ),
        migrations.AlterField(
            model_name='batchtostudentmessagesdata',
            name='StudentId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='StudentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Data_API.studentdata'),
        ),
    ]
