# Generated by Django 5.0.6 on 2024-08-30 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0008_alter_batchattendance_batchid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentattendance',
            old_name='StudentID',
            new_name='StudentId',
        ),
    ]
