# Generated by Django 5.0.6 on 2024-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0010_studentattendance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='BatchName',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Educational_Info',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Permission',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Personal_Info',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Placement_Info',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='Status',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
