# Generated by Django 5.0.6 on 2024-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0011_remove_studentdata_batchname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='BatchName',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Course',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Educational_Info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Email',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Permission',
            field=models.CharField(default='Access', max_length=25),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Personal_Info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Phone',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Placement_Info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Status',
            field=models.CharField(default='Active', max_length=255),
        ),
    ]
