# Generated by Django 5.0.6 on 2024-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0012_studentdata_batchname_studentdata_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Student_Config',
            field=models.BinaryField(default=b''),
        ),
    ]
