# Generated by Django 5.0.6 on 2024-09-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0013_studentdata_student_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecordingsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Title', models.CharField(default='N/A', max_length=255)),
                ('Date', models.CharField(default='N/A', max_length=255)),
                ('Vedio_URL', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentWatchTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='N/A', max_length=255)),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Date', models.CharField(default='N/A', max_length=255)),
                ('VedioDetails', models.TextField()),
                ('StudentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchtime', to='Data_API.studentdata')),
            ],
        ),
    ]
