# Generated by Django 5.0.6 on 2024-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0014_classrecordingsdata_studentwatchtimedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Edit_Access', models.CharField(default='Denied', max_length=25)),
                ('Login_Access', models.CharField(default='Access', max_length=25)),
            ],
        ),
    ]
