# Generated by Django 5.0.6 on 2024-09-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0015_permissionsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFormLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('FeedbackData', models.JSONField(default=dict)),
                ('Selected', models.BooleanField(default=False)),
            ],
        ),
    ]
