# Generated by Django 5.0.6 on 2024-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0016_feedbackformlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchdata',
            name='Date',
            field=models.CharField(default='N/A', max_length=225),
        ),
        migrations.AddField(
            model_name='coursesdata',
            name='Date',
            field=models.CharField(default='N/A', max_length=225),
        ),
    ]
