# Generated by Django 5.0.6 on 2024-09-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0019_reportdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionsdata',
            name='Batch_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Data_API.batchdata'),
        ),
    ]
