# Generated by Django 5.0.6 on 2024-09-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0020_permissionsdata_batch_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionsdata',
            old_name='Batch_ID',
            new_name='BatchID',
        ),
        migrations.AddField(
            model_name='batchmessagesdata',
            name='BatchID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_messages', to='Data_API.batchdata'),
        ),
        migrations.AddField(
            model_name='studentmessagesdata',
            name='StudentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_messages', to='Data_API.studentdata'),
        ),
    ]
