# Generated by Django 5.0.6 on 2024-09-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0023_usersvaultdata_userslogindata_vaultpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersVaultData',
            new_name='UsersDriveData',
        ),
        migrations.RenameField(
            model_name='userslogindata',
            old_name='VaultPassword',
            new_name='DrivePassword',
        ),
    ]
