# Generated by Django 5.0.6 on 2024-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0024_rename_usersvaultdata_usersdrivedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='Status',
            field=models.CharField(default='UnSolved', max_length=255),
        ),
    ]
