# Generated by Django 5.0.6 on 2024-09-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0025_reportdata_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwatchtimedata',
            name='VedioDetails',
        ),
        migrations.AddField(
            model_name='studentwatchtimedata',
            name='WatchTime',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
