# Generated by Django 5.0.6 on 2024-10-05 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0027_assessmentquestionsdata_weeklyassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWeeklyTestResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='N/A', max_length=255)),
                ('Course', models.CharField(default='N/A', max_length=255)),
                ('BatchName', models.CharField(default='N/A', max_length=255)),
                ('Date', models.CharField(default='N/A', max_length=255)),
                ('Status', models.CharField(default='N/A', max_length=255)),
                ('Score', models.CharField(default='N/A', max_length=255)),
                ('StudentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_test_results', to='Data_API.studentdata')),
            ],
        ),
    ]
