# Generated by Django 5.0.6 on 2024-10-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0028_studentweeklytestresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentweeklytestresults',
            name='Score',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
