# Generated by Django 5.0.6 on 2024-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0030_studentrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweeklytestresults',
            name='Time',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
