# Generated by Django 5.0.6 on 2024-10-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_API', '0031_studentweeklytestresults_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentweeklytestresults',
            name='Image',
            field=models.TextField(default='N/A'),
        ),
    ]
